# These are supported funding model platforms
# github: metawake  # Not available in Montenegro
ko_fi: metawake
# buy_me_a_coffee: metawake
custom: ["https://etherscan.io/address/0x0a542565b3615e8fc934cc3cc4921a0c22e5dc5e"]

