# These are supported funding model platforms
# github: metawake  # Not available in Montenegro
# ko_fi: metawake
# buy_me_a_coffee: metawake
custom: ["https://github.com/metawake/multi-chain-balance-diff#support-development"]

